import type { Ontology, OntologyEntity, OntologyRelations } from "../types/ontology-types.ts";

const TTL_HEADER = `@prefix : <http://edugraph.io/edu/> .
@prefix edu: <http://edugraph.io/edu#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://edugraph.io/edu/> .

<http://edugraph.io/edu/> rdf:type owl:Ontology ;
                           owl:imports edu: .

#################################################################
#    Individuals
#################################################################
`;

const TTL_FOOTER = `

###  Generated by the EduGraph Editor`;

const formatMultiLine = (text: string) => {
    return `"""${text}"""`;
};

const serializeEntity = (entity: OntologyEntity, relations: OntologyRelations, dimension: string): string => {
    let ttlString = `
###  http://edugraph.io/edu/${entity.name}
`;
    ttlString += `:${entity.name} rdf:type owl:NamedIndividual ,
`;
    ttlString += `                             edu:${dimension} ;`;

    const entityRelations: { pred: string; obj: string }[] = [];

    // Collect all relationships for the current entity
    for (const relationKey in relations) {
        const rel = relationKey as keyof OntologyRelations;
        if (relations[rel]?.[entity.iri]) {
            relations[rel]![entity.iri].forEach(objectIri => {
                const objectName = objectIri.replace('http://edugraph.io/edu/', '');
                entityRelations.push({ pred: `edu:${rel}`, obj: `:${objectName}` });
            });
        }
    }
    
    // Sort relations alphabetically
    entityRelations.sort((a, b) => a.pred.localeCompare(b.pred));

    entityRelations.forEach(rel => {
        ttlString += `
                    ${rel.pred} ${rel.obj} ;`;
    });

    if (entity.examples) {
        ttlString += `
                    rdfs:comment ${formatMultiLine(entity.examples)} ;`;
    }
    if (entity.definition) {
        ttlString += `
                    rdfs:isDefinedBy ${formatMultiLine(entity.definition)} ;`;
    }

    // Clean up trailing semicolon
    if (ttlString.endsWith(';')) {
        ttlString = ttlString.slice(0, -1) + '.';
    } else {
        // If there were no relations or comments/definitions, the last character is the dimension type
        ttlString += ' .';
    }


    return ttlString;
};

export const serializeOntology = (ontology: Ontology, dimension: 'Area' | 'Ability' | 'Scope'): string => {
    let individualsString = "";

    const sortedEntities = [...ontology.entities].sort((a, b) => a.name.localeCompare(b.name));

    for (const entity of sortedEntities) {
        individualsString += serializeEntity(entity, ontology.relations, dimension);
    }

    return TTL_HEADER + individualsString + TTL_FOOTER;
};
