import type { Ontology, OntologyEntity, OntologyRelations } from "../types/ontology-types.ts";

const TTL_HEADER = `@prefix : <http://edugraph.io/edu/> .
@prefix edu: <http://edugraph.io/edu#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@base <http://edugraph.io/edu/> .

<http://edugraph.io/edu/> rdf:type owl:Ontology ;
                           owl:imports edu: .

#################################################################
#    Individuals
#################################################################`;

const TTL_FOOTER = `###  Generated by the OWL API (version 4.5.29.2024-05-13T12:11:03Z) https://github.com/owlcs/owlapi`;

const formatLiteral = (text: string): string => {
    if (!text || !text.includes('\n')) {
        return `"${text || ''}"`;
    }
    return `"""${text}"""`;
};

const serializeEntity = (entity: OntologyEntity, relations: OntologyRelations, dimension: string): string => {
    let ttlString = `\n\n###  http://edugraph.io/edu/${entity.name}\n`;
    ttlString += `:${entity.name} rdf:type owl:NamedIndividual ,\n`;
    ttlString += `                   edu:${dimension} ;`;

    const groupedRelations: { [key: string]: string[] } = {};

    const relationKeys = Object.keys(relations) as Array<keyof OntologyRelations>;
    relationKeys.sort();
    
    for (const relationKey of relationKeys) {
        const subjects = relations[relationKey];
        if (subjects && subjects[entity.iri]) {
            const objectIris = subjects[entity.iri];
            const pred = `edu:${relationKey}`;
            if (!groupedRelations[pred]) {
                groupedRelations[pred] = [];
            }
            objectIris.forEach(objIri => {
                groupedRelations[pred].push(`:${objIri.replace('http://edugraph.io/edu/', '')}`);
            });
        }
    }
    
    const sortedPredicates = Object.keys(groupedRelations).sort();

    sortedPredicates.forEach(pred => {
        const objects = groupedRelations[pred];
        if (objects.length > 1) {
            ttlString += `\n          ${pred} ${objects.join(' ,\n                  ')} ;`;
        } else {
            ttlString += `\n          ${pred} ${objects[0]} ;`;
        }
    });

    if (entity.examples) {
        ttlString += `\n          rdfs:comment ${formatLiteral(entity.examples)} ;`;
    }
    if (entity.definition) {
        ttlString += `\n          rdfs:isDefinedBy ${formatLiteral(entity.definition)} ;`;
    }

    if (ttlString.endsWith(';')) {
        ttlString = ttlString.slice(0, -1) + '.';
    } else {
        ttlString += ' .';
    }

    return ttlString;
};

export const serializeOntology = (ontology: Ontology, dimension: 'Area' | 'Ability' | 'Scope'): string => {
    const sortedEntities = [...ontology.entities].sort((a, b) => a.iri.localeCompare(b.iri));
    const individualsString = sortedEntities.map(entity => serializeEntity(entity, ontology.relations, dimension)).join('');
    return TTL_HEADER + individualsString + "\n\n\n" + TTL_FOOTER;
};
